version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    steps:
        - checkout

        - run:
            name: Set Ruby Version
            command: echo "ruby-2.3.3" > ~/.ruby-versio
        
        - run:
            name: Install
            command: bundle install
        
        - run:
            name: Build
            command: bundle exec fastlane beta 
