# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
  	increment_build_number
  	match(
  		type: 'adhoc',
  		app_identifier: ''
		)
	gym(
		project: 'Hello World CI.xcodeproj',
		scheme: 'Hello World CI',
		clean: true,
		export_method: 'ad-hoc'
		)
	hockey(
		api_token: '66062575166d4e94843aa04a2a7d9349'
		)
	
	end
end
